_BASE_: [
  '../base.yaml',
]

input_path:
  'test/data/videos/MOT17-03-partial.mp4'

output_path:
  ./deploy_res

vis_flag:
  True

adadet_deploy:
  type: MOTCounting
  model_id: 'damo/cv_yolov5_video-multi-object-tracking_fairmot'
  rules:
    is_video: True
    horizontal: True
    coord: 200
    in_flag: True
